import React from "react";
import s from './Header.module.css';

const Header = () => {
  return (
    <header className={s.header}>
      <img src="https://app.logoza.ru/?logo=eyJsYXlvdXQiOiJzdHlsZS0xIiwiYmFja2dyb3VuZENvbG9yIjoiI2ZmZmZmZiIsImNhbnZhc1dpZHRoIjo3MDAsImNhbnZhc0hlaWdodCI6NDQwLCJnYXAiOjEwLCJpY29uIjp7ImVuYWJsZWQiOiJ5ZXMiLCJmaWxlIjoiaWNvbnMvc3ltYm9sL2F0b21fNWU0Zjg2MjM0MjE0N19sb2dvemEuc3ZnIiwieE9mZnNldCI6LTIwMCwieU9mZnNldCI6LTE0LCJzY2FsZVdpZHRoIjoxMDUsImFuZ2xlIjowLCJza2V3WCI6MCwic2tld1kiOjAsImZsaXBYIjoibm8iLCJmbGlwWSI6Im5vIiwiZmlsbEVuYWJsZWQiOiJ5ZXMiLCJmaWxsIjoiIzNEOEVCOSIsImZpbGxTdHJva2VzIjoieWVzIiwiY29sb3JTaGlmdCI6MCwiYnJpZ2h0bmVzcyI6MCwiZ3JheXNjYWxlIjowLCJzaGFkb3dYIjoxLCJzaGFkb3dZIjowLCJzaGFkb3dXaWR0aCI6MCwic2hhZG93Q29sb3IiOiJyZ2JhKDAsMCwwLDAuNSkiLCJwYWxldHRlIjoiIn0sInRpdGxlIjp7InRleHQiOiJMZWdhYm9nIiwidGV4dEFsaWduIjoibGVmdCIsImZvbnRGYW1pbHkiOiJQcmVzcyBTdGFydCAyUCIsImZvbnRTaXplIjo0OCwiZm9udFdlaWdodCI6NzAwLCJmb250U3R5bGUiOiJub3JtYWwiLCJsaW5lSGVpZ2h0IjoxLCJjaGFyU3BhY2luZyI6MCwidW5kZXJsaW5lIjoibm8iLCJvdmVybGluZSI6Im5vIiwibGluZXRocm91Z2giOiJubyIsImZpbGwiOiIjMDAwMDAwIiwiZmlsbEdyYWRpZW50Ijoibm8iLCJncmFkaWVudFR5cGUiOiJob3Jpem9udGFsIiwiZ3JhZGllbnRTdGVwcyI6IiNmZjAwMDAsI2ZmZmYwMCIsImJhY2tncm91bmRDb2xvciI6IiMxREFCQjgiLCJiYWNrZ3JvdW5kRW5hYmxlZCI6Im5vIiwic3Ryb2tlIjoiIzAwMDAwMCIsInN0cm9rZVdpZHRoIjowLCJzaGFkb3dYIjowLCJzaGFkb3dZIjowLCJzaGFkb3dXaWR0aCI6MCwic2hhZG93Q29sb3IiOiJyZ2JhKDAsMCwwLC41KSIsInhPZmZzZXQiOi0yMDAsInlPZmZzZXQiOjAsImFuZ2xlIjowLCJza2V3WCI6MCwic2tld1kiOjAsInNjYWxlIjoxfSwic2xvZ2FuIjp7ImVuYWJsZWQiOiJubyIsInRleHQiOiLRgdC70L7Qs9Cw0L0iLCJ0ZXh0QWxpZ24iOiJsZWZ0IiwiZm9udEZhbWlseSI6Ik9wZW4gU2FucyIsImZvbnRTaXplIjoyMSwiZm9udFdlaWdodCI6NDAwLCJmb250U3R5bGUiOiJub3JtYWwiLCJsaW5lSGVpZ2h0IjoxLCJjaGFyU3BhY2luZyI6MCwiZmlsbCI6IiMwMDAwMDAiLCJmaWxsR3JhZGllbnQiOiJubyIsImdyYWRpZW50VHlwZSI6Imhvcml6b250YWwiLCJncmFkaWVudFN0ZXBzIjoiI2ZmZmYwMCwjZmYwMDAwIiwiYmFja2dyb3VuZENvbG9yIjoiIzgzRDZERSIsImJhY2tncm91bmRFbmFibGVkIjoibm8iLCJzdHJva2UiOiIjMDAwMDAwIiwic3Ryb2tlV2lkdGgiOjAsInNoYWRvd1giOjAsInNoYWRvd1kiOjAsInNoYWRvd1dpZHRoIjowLCJzaGFkb3dDb2xvciI6InJnYmEoMCwwLDAsLjUpIiwieE9mZnNldCI6MCwieU9mZnNldCI6MCwiYW5nbGUiOjAsInNrZXdYIjowLCJza2V3WSI6MCwic2NhbGUiOjF9fQ==" />
    </header>
  );
};

export default Header
